---

- name: load default
  include_vars:
    file: default.yml
    name: "default"

- name: load OS family map
  include_vars:
    file: osfamilymap.yml
    name: "osfamilymap"

- name: load distribution map
  include_vars:
    file: distributionmap.yml
    name: "distributionmap"

- name: compute configuration
  set_fact:
    nslcd: "{{ default.nslcd | combine(
      osfamilymap[ansible_os_family].nslcd is defined | ternary(osfamilymap[ansible_os_family].nslcd, {}),
      distributionmap[ansible_distribution].nslcd is defined | ternary(distributionmap[ansible_distribution].nslcd, {}),
      nslcd | default({}),
      recursive=True
      ) }}"
