---

- name: load variables
  include_vars:
    file: "{{ map }}.yml"
    name: "{{ map }}"
  loop:
    - default
    - osfamilymap
    - distributionmap
    - fingerprintmap
  loop_control:
    loop_var: map

- name: compute fingerprint
  set_fact:
    ansible_fingerprint: "{{ ansible_distribution+(ansible_distribution_major_version != 'NA') | ternary(ansible_distribution_major_version, '') }}"

- name: compute configuration
  set_fact:
    nslcd: "{{ default.nslcd | default({}) | combine(
      osfamilymap[ansible_os_family].nslcd is defined | ternary(osfamilymap[ansible_os_family].nslcd, {}),
      distributionmap[ansible_distribution].nslcd is defined | ternary(distributionmap[ansible_distribution].nslcd, {}),
      fingerprintmap[ansible_fingerprint].nslcd is defined | ternary(fingerprintmap[ansible_fingerprint].nslcd, {}),
      nslcd | default({}),
      recursive=True
      ) }}"
